
#include <stdio.h>
int main()
{
    int branches,products;
    float revenue[50];          // revenue per unit for each product
    int shipped[50][50];        // shipped units per branch and product
    float trevenue[50];         // total revenue per branch
    int i,j;
    // Input number of branches and products
    printf("Enter number of branches:");
    scanf("%d", &branches);

    printf("Enter number of products:");
    scanf("%d", &products);
    // Input revenue per unit for each product
    printf("Enter revenue per unit for each of the %d products:\n", products);
    for(j=0;j<products;j++)
    {
        scanf("%f",&revenue[j]);
    }
    // Input shipped units
    printf("Enter units shipped:\n");
    for(i=0;i<branches;i++)
    {
        printf("Branch %d:\n",i+1);
        for(j=0;j<products;j++)
        {
            scanf("%d",&shipped[i][j]);
        }
    }

    // Calculate total revenue for each branch
    for(i=0;i<branches;i++)
    {
        trevenue[i]=0;
        for(j=0;j<products;j++)
        {
            trevenue[i]= trevenue[i]+(shipped[i][j]*revenue[j]);
        }
    }
    printf("Total Revenue generated by each branch:\n");
    for(i=0;i<branches;i++)
    {
        printf("Branch %d: .2%f\n",i+1,trevenue[i]);
    }

    return 0;
}


    /* Total Revenue = Revenue per unit for each product*Units shipped 
       in each branch */
    